#!/bin/bash
# AmneziaWG container entrypoint: renders awg0.conf from environment
# (unique per installation — generated by deploy/install.sh) and brings
# the interface up in userspace mode (amneziawg-go, no kernel module).
set -euo pipefail

CONF_DIR=/etc/amnezia/amneziawg
CONF=$CONF_DIR/awg0.conf
mkdir -p "$CONF_DIR"

# Required variables are rendered by install.sh into deploy/awg/awg0.conf
# directly; this script only applies sysctl-safe settings and starts AWG.
if [ ! -f "$CONF" ]; then
    echo "[awg] $CONF not found — run deploy/install.sh first" >&2
    exit 1
fi
chmod 600 "$CONF"

# Userspace WireGuard needs a TUN device.
mkdir -p /dev/net
[ -c /dev/net/tun ] || mknod /dev/net/tun c 10 200 || true

amneziawg-go awg0 &
AWG_PID=$!

# Wait for the interface, then apply the config.
for _ in $(seq 1 30); do
    ip link show awg0 >/dev/null 2>&1 && break
    sleep 0.5
done

awg setconf awg0 <(awg-quick strip awg0 2>/dev/null || cat "$CONF")
ip address replace "${AWG_ADDRESS:-10.13.13.1/24}" dev awg0
ip link set mtu "${AWG_MTU:-1280}" up dev awg0

echo "[awg] awg0 up on UDP ${AWG_PORT:-51820} (MTU ${AWG_MTU:-1280})"
awg show awg0

wait $AWG_PID
